{"name": "Проверка,если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "start": 1758314375307, "stop": 1758314375415, "uuid": "a9aa41cc-e647-48d7-b247-6809712618d2", "historyId": "cdef4ee27e02a674b1760656e99045fb", "testCaseId": "cdef4ee27e02a674b1760656e99045fb", "fullName": "tests.test_creating_courier.TestCourier#test_creating_courier_with_the_same_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestCourier"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}], "titlePath": ["tests", "test_creating_courier.py", "TestCourier"]}