{"name": "Проверка присвоения заказа с неверными параметрами", "status": "passed", "parameters": [{"name": "response_expected", "value": "{'code': 404, 'message': 'Not Found.'}"}, {"name": "wrong_data", "value": "{'order_id': ''}"}], "start": 1758314304563, "stop": 1758314304898, "uuid": "270b7acb-788f-417b-aff5-30fac3484d17", "historyId": "98a232cf707eb63d38afc8cbbf17662f", "testCaseId": "95ac7c73cec1d8ec3815307c1194dfc5", "fullName": "tests.test_courier_accept_orders.TestCourierAcceptOrder#test_courier_accept_order_with_wrong_params", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_accept_orders"}, {"name": "subSuite", "value": "TestCourierAcceptOrder"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_accept_orders"}], "titlePath": ["tests", "test_courier_accept_orders.py", "TestCourierAcceptOrder"]}