{"name": "Проверка присвоения заказа с неверными параметрами", "status": "passed", "parameters": [{"name": "response_expected", "value": "{'code': 404, 'message': 'Заказа с таким id не существует'}"}, {"name": "wrong_data", "value": "{'order_id': -1}"}], "start": 1758314303851, "stop": 1758314304153, "uuid": "c55f9303-616b-4190-80be-dca9723915fc", "historyId": "27ea729895a4353f6249416438ff5c79", "testCaseId": "95ac7c73cec1d8ec3815307c1194dfc5", "fullName": "tests.test_courier_accept_orders.TestCourierAcceptOrder#test_courier_accept_order_with_wrong_params", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_accept_orders"}, {"name": "subSuite", "value": "TestCourierAcceptOrder"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_accept_orders"}], "titlePath": ["tests", "test_courier_accept_orders.py", "TestCourierAcceptOrder"]}