{"name": "Система вернёт ошибку при неверном пароле", "status": "passed", "steps": [{"name": "Попытка авторизации с неверным паролем", "status": "passed", "start": 1758473563358, "stop": 1758473563439}, {"name": "Проверка ожидаемой ошибки", "status": "passed", "start": 1758473563439, "stop": 1758473563439}], "parameters": [{"name": "password_value", "value": "''"}, {"name": "expected_response", "value": "{'code': 400, 'message': 'Недостаточно данных для входа'}"}], "start": 1758473563358, "stop": 1758473563440, "uuid": "a34ed68d-83f6-489f-9f3f-b18df5016aca", "historyId": "85bd8e877b7b574b491816591677cd9a", "testCaseId": "83ee3d8b7704c3c147d5420c7fb48d7d", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_with_invalid_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "13416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}